/*
 *      Copyright (C) 2008-2012 Liviu Ionescu.
 *
 *      This file is part of the uOS++ distribution.
 */

#ifndef DEVICECANTRANSCEIVER_DEFINES_H_
#define DEVICECANTRANSCEIVER_DEFINES_H_

#define  OS_CONFIG_DEVICECANTRANSCEIVER_RS_PORT_CONFIG  DDRC
#define  OS_CONFIG_DEVICECANTRANSCEIVER_RS_PORT_WRITE   PORTC
#define  OS_CONFIG_DEVICECANTRANSCEIVER_RS_BIT          0

#endif /* DEVICECANTRANSCEIVER_DEFINES_H_ */
