/*
 *      Copyright (C) 2008-2012 Liviu Ionescu.
 *
 *      This file is part of the uOS++ distribution.
 */

#ifndef HAL_BOARD_DEVICEMEMCARDSELECT_DEFINES_H_
#define HAL_BOARD_DEVICEMEMCARDSELECT_DEFINES_H_

#define OS_CONFIG_DEVICEMEMCARDSELECT_PORT_CONFIG      	DDRB
#define OS_CONFIG_DEVICEMEMCARDSELECT_PORT_WRITE	PORTB
#define OS_CONFIG_DEVICEMEMCARDSELECT_PORT_BIT          0

#endif /* HAL_BOARD_DEVICEMEMCARDSELECT_DEFINES_H_ */
