
flash-run:	all
	openocd -f "../../micro-os-plus/system/scripts/ocd/olimex-arm-usb-ocd-A.cfg" -f "../../micro-os-plus/system/scripts/ocd/stm32.cfg" -f "../../micro-os-plus/system/scripts/ocd/flash-write-prepare.cfg" -c "flash write_image minimal.hex 0x08000000 ihex" -c "mdw 0x00000000 8" -c "reset run" -c "shutdown"

env:
	env


avr32-size:  $(TARGET).elf
	avr32-size $(TARGET).elf

.IGNORE: avr32-dfu-run

avr32-dfu-run: all
	avr32-objcopy -O ihex $(TARGET).elf $(TARGET).ihex
	avr32-size $(TARGET).elf
	dfu-programmer $(DFU-MCU) erase
	dfu-programmer $(DFU-MCU) flash --suppress-bootloader-mem $(TARGET).ihex
	-dfu-programmer $(DFU-MCU) start
	@echo "Done"